language: csharp

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.1.0

before_install:
  - git config --global core.autocrlf true

install:
  - dotnet restore --source https://api.nuget.org/v3/index.json --source https://powershell.myget.org/F/powershell-core/api/v3/index.json

matrix:
  include:
    
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.1.0
      env: configuration=debug
    
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.1.0
      env: configuration=release

    - os: osx # OSX 10.12
      osx_image: xcode8.2
      dotnet: 1.1.0
      env: configuration=debug
    
    - os: osx # OSX 10.12
      osx_image: xcode8.2
      dotnet: 1.1.0
      env: configuration=release

script:
  - dotnet build src/LocalAppVeyor.Engine --configuration %configuration%
  - dotnet build src/LocalAppVeyor --configuration %configuration%
  - dotnet test tests/LocalAppVeyor.Engine.UnitTests/LocalAppVeyor.Engine.UnitTests.csproj --configuration %configuration%
