image: Visual Studio 2017

version: 0.5.0-alpha8+appveyor.{build}

init:
  - choco install dotnetcore-sdk
  - dotnet --info
  - git config --global core.autocrlf true

configuration:
  - debug
  - release

before_build:
  - dotnet restore --source https://api.nuget.org/v3/index.json --source https://powershell.myget.org/F/powershell-core/api/v3/index.json

build_script:
  - dotnet build src\LocalAppVeyor.Engine --configuration %configuration%
  - dotnet build src\LocalAppVeyor --configuration %configuration%

after_build:
  - dotnet pack src\LocalAppVeyor.Engine --configuration %configuration% --output out_engine
  - dotnet pack src\LocalAppVeyor --configuration %configuration% --output out_console

test_script:
  - dotnet test tests\LocalAppVeyor.Engine.UnitTests\LocalAppVeyor.Engine.UnitTests.csproj --configuration %configuration%

artifacts:
  - path: src\LocalAppVeyor.Engine\out_engine\*.nupkg
    name: engine_packages
  - path: src\LocalAppVeyor\out_console\*.nupkg
    name: console_packages

deploy:
  - provider: NuGet
    api_key: 
      secure: 1hAXpLden83UvMID3arEUevAp6zBH5hZOz6RgSP/werUFR6ek4/9/ZoTDfKbnfX8
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: engine_packages

  - provider: NuGet
    api_key: 
      secure: ZptAP8p6YvAsJmPh9iagQBpkz1h8ppRxNAe2yT6TEXGr0B5zpQ3jwm6uWg/VKx6X
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: console_packages