version: 0.5.0-alpha3+appveyor.{build}


init:
  - git config --global core.autocrlf true


configuration:
  - debug
  - release


install:
  - nuget sources add -Name PowerShellMyGet -Source https://powershell.myget.org/F/powershell-core/api/v3/index.json


before_build:
  - dotnet restore

build_script:
  - dotnet build src\LocalAppVeyor.Engine\project.json --configuration %configuration%
  - dotnet build src\LocalAppVeyor\project.json --configuration %configuration%


after_build:
  - dotnet pack src\LocalAppVeyor.Engine\project.json --configuration %configuration% --output out_engine
  - dotnet pack src\LocalAppVeyor\project.json --configuration %configuration% --output out_console


test_script:
  - dotnet test tests\LocalAppVeyor.Engine.UnitTests\project.json --configuration %configuration%


artifacts:
  - path: out_engine\*.nupkg
    name: engine_packages
  - path: out_console\*.nupkg
    name: console_packages


deploy:
  - provider: NuGet
    api_key: 
      secure: sQplMyrjV8N58rccFtWBFZcsjJy6iHKKP9DbSxRAds10jrfshfM+JorTBMyN8wOs
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: engine_packages

  - provider: NuGet
    api_key: 
      secure: sQplMyrjV8N58rccFtWBFZcsjJy6iHKKP9DbSxRAds10jrfshfM+JorTBMyN8wOs
    on:
      branch: master
      appveyor_repo_tag: true
      configuration: release
    skip_symbols: true
    artifact: console_packages